package family

// One tag with its resolved member entries
type syncedTag struct {
	name    string
	entries []string
}

// Tags for one registry in wire order
type syncedTagRegistry struct {
	name string
	tags []syncedTag
}

// Tables below mirror flattened vanilla tag data
// Block members are static ids the panel lacks, names bind empty
var tagsDialog = []syncedTag{
	{name: "minecraft:pause_screen_additions"},
	{name: "minecraft:quick_actions"},
}

var tagsTimeline = []syncedTag{
	{name: "minecraft:in_end", entries: []string{"villager_schedule"}},
	{name: "minecraft:in_nether", entries: []string{"villager_schedule"}},
	{name: "minecraft:in_overworld", entries: []string{"villager_schedule", "day", "moon", "early_game"}},
	{name: "minecraft:universal", entries: []string{"villager_schedule"}},
}

var tagsDamage775 = []syncedTag{
	{name: "minecraft:always_hurts_ender_dragons", entries: []string{"fireworks", "explosion", "player_explosion", "bad_respawn_point"}},
	{name: "minecraft:always_kills_armor_stands", entries: []string{"arrow", "trident", "fireball", "wither_skull", "wind_charge"}},
	{name: "minecraft:always_most_significant_fall", entries: []string{"out_of_world"}},
	{name: "minecraft:always_triggers_silverfish", entries: []string{"magic"}},
	{name: "minecraft:avoids_guardian_thorns", entries: []string{"magic", "thorns", "fireworks", "explosion", "player_explosion", "bad_respawn_point"}},
	{name: "minecraft:burn_from_stepping", entries: []string{"campfire", "hot_floor"}},
	{name: "minecraft:burns_armor_stands", entries: []string{"on_fire"}},
	{name: "minecraft:bypasses_armor", entries: []string{"on_fire", "in_wall", "cramming", "drown", "fly_into_wall", "generic", "wither", "dragon_breath", "starve", "fall", "ender_pearl", "freeze", "stalagmite", "magic", "indirect_magic", "out_of_world", "generic_kill", "sonic_boom", "outside_border"}},
	{name: "minecraft:bypasses_effects", entries: []string{"starve"}},
	{name: "minecraft:bypasses_enchantments", entries: []string{"sonic_boom"}},
	{name: "minecraft:bypasses_invulnerability", entries: []string{"out_of_world", "generic_kill"}},
	{name: "minecraft:bypasses_resistance", entries: []string{"out_of_world", "generic_kill"}},
	{name: "minecraft:bypasses_shield", entries: []string{"on_fire", "in_wall", "cramming", "drown", "fly_into_wall", "generic", "wither", "dragon_breath", "starve", "fall", "ender_pearl", "freeze", "stalagmite", "magic", "indirect_magic", "out_of_world", "generic_kill", "sonic_boom", "outside_border", "cactus", "campfire", "dry_out", "falling_anvil", "falling_stalactite", "hot_floor", "in_fire", "lava", "lightning_bolt", "sweet_berry_bush"}},
	{name: "minecraft:bypasses_wolf_armor", entries: []string{"out_of_world", "generic_kill", "cramming", "drown", "dry_out", "freeze", "in_wall", "indirect_magic", "magic", "outside_border", "starve", "thorns", "wither"}},
	{name: "minecraft:can_break_armor_stand", entries: []string{"player_explosion", "player_attack", "spear", "mace_smash"}},
	{name: "minecraft:damages_helmet", entries: []string{"falling_anvil", "falling_block", "falling_stalactite"}},
	{name: "minecraft:ignites_armor_stands", entries: []string{"in_fire", "campfire"}},
	{name: "minecraft:is_drowning", entries: []string{"drown"}},
	{name: "minecraft:is_explosion", entries: []string{"fireworks", "explosion", "player_explosion", "bad_respawn_point"}},
	{name: "minecraft:is_fall", entries: []string{"fall", "ender_pearl", "stalagmite"}},
	{name: "minecraft:is_fire", entries: []string{"in_fire", "campfire", "on_fire", "lava", "hot_floor", "unattributed_fireball", "fireball"}},
	{name: "minecraft:is_freezing", entries: []string{"freeze"}},
	{name: "minecraft:is_lightning", entries: []string{"lightning_bolt"}},
	{name: "minecraft:is_player_attack", entries: []string{"player_attack", "spear", "mace_smash"}},
	{name: "minecraft:is_projectile", entries: []string{"arrow", "trident", "mob_projectile", "unattributed_fireball", "fireball", "wither_skull", "thrown", "wind_charge"}},
	{name: "minecraft:mace_smash", entries: []string{"mace_smash"}},
	{name: "minecraft:no_anger", entries: []string{"mob_attack_no_aggro"}},
	{name: "minecraft:no_impact", entries: []string{"drown"}},
	{name: "minecraft:no_knockback", entries: []string{"explosion", "player_explosion", "bad_respawn_point", "in_fire", "lightning_bolt", "on_fire", "lava", "hot_floor", "in_wall", "cramming", "drown", "starve", "cactus", "fall", "ender_pearl", "fly_into_wall", "out_of_world", "generic", "magic", "wither", "dragon_breath", "dry_out", "sweet_berry_bush", "freeze", "stalagmite", "outside_border", "generic_kill", "campfire", "spear"}},
	{name: "minecraft:panic_causes", entries: []string{"cactus", "freeze", "hot_floor", "in_fire", "lava", "lightning_bolt", "on_fire", "arrow", "dragon_breath", "explosion", "fireball", "fireworks", "indirect_magic", "magic", "mob_attack", "mob_projectile", "player_explosion", "sonic_boom", "sting", "thrown", "trident", "unattributed_fireball", "wind_charge", "wither", "wither_skull", "player_attack", "spear", "mace_smash"}},
	{name: "minecraft:panic_environmental_causes", entries: []string{"cactus", "freeze", "hot_floor", "in_fire", "lava", "lightning_bolt", "on_fire"}},
	{name: "minecraft:witch_resistant_to", entries: []string{"magic", "indirect_magic", "sonic_boom", "thorns"}},
	{name: "minecraft:wither_immune_to", entries: []string{"drown"}},
}

var tagsDamage776 = []syncedTag{
	{name: "minecraft:always_hurts_ender_dragons", entries: []string{"fireworks", "explosion", "player_explosion", "bad_respawn_point"}},
	{name: "minecraft:always_kills_armor_stands", entries: []string{"arrow", "trident", "fireball", "wither_skull", "wind_charge"}},
	{name: "minecraft:always_most_significant_fall", entries: []string{"out_of_world"}},
	{name: "minecraft:always_triggers_silverfish", entries: []string{"magic"}},
	{name: "minecraft:avoids_guardian_thorns", entries: []string{"magic", "thorns", "fireworks", "explosion", "player_explosion", "bad_respawn_point"}},
	{name: "minecraft:burn_from_stepping", entries: []string{"campfire", "hot_floor", "sulfur_cube_hot"}},
	{name: "minecraft:burns_armor_stands", entries: []string{"on_fire"}},
	{name: "minecraft:bypasses_armor", entries: []string{"on_fire", "in_wall", "cramming", "drown", "fly_into_wall", "generic", "wither", "dragon_breath", "starve", "fall", "ender_pearl", "freeze", "stalagmite", "magic", "indirect_magic", "out_of_world", "generic_kill", "sonic_boom", "outside_border"}},
	{name: "minecraft:bypasses_effects", entries: []string{"starve"}},
	{name: "minecraft:bypasses_enchantments", entries: []string{"sonic_boom"}},
	{name: "minecraft:bypasses_invulnerability", entries: []string{"out_of_world", "generic_kill"}},
	{name: "minecraft:bypasses_resistance", entries: []string{"out_of_world", "generic_kill"}},
	{name: "minecraft:bypasses_shield", entries: []string{"on_fire", "in_wall", "cramming", "drown", "fly_into_wall", "generic", "wither", "dragon_breath", "starve", "fall", "ender_pearl", "freeze", "stalagmite", "magic", "indirect_magic", "out_of_world", "generic_kill", "sonic_boom", "outside_border", "cactus", "campfire", "dry_out", "falling_anvil", "falling_stalactite", "hot_floor", "sulfur_cube_hot", "in_fire", "lava", "lightning_bolt", "sweet_berry_bush"}},
	{name: "minecraft:bypasses_wolf_armor", entries: []string{"out_of_world", "generic_kill", "cramming", "drown", "dry_out", "freeze", "in_wall", "indirect_magic", "magic", "outside_border", "starve", "thorns", "wither"}},
	{name: "minecraft:can_break_armor_stand", entries: []string{"player_explosion", "player_attack", "spear", "mace_smash"}},
	{name: "minecraft:damages_helmet", entries: []string{"falling_anvil", "falling_block", "falling_stalactite"}},
	{name: "minecraft:ignites_armor_stands", entries: []string{"in_fire", "campfire"}},
	{name: "minecraft:is_drowning", entries: []string{"drown"}},
	{name: "minecraft:is_explosion", entries: []string{"fireworks", "explosion", "player_explosion", "bad_respawn_point"}},
	{name: "minecraft:is_fall", entries: []string{"fall", "ender_pearl", "stalagmite"}},
	{name: "minecraft:is_fire", entries: []string{"in_fire", "campfire", "on_fire", "lava", "hot_floor", "sulfur_cube_hot", "unattributed_fireball", "fireball"}},
	{name: "minecraft:is_freezing", entries: []string{"freeze"}},
	{name: "minecraft:is_lightning", entries: []string{"lightning_bolt"}},
	{name: "minecraft:is_player_attack", entries: []string{"player_attack", "spear", "mace_smash"}},
	{name: "minecraft:is_projectile", entries: []string{"arrow", "trident", "mob_projectile", "unattributed_fireball", "fireball", "wither_skull", "thrown", "wind_charge"}},
	{name: "minecraft:mace_smash", entries: []string{"mace_smash"}},
	{name: "minecraft:no_anger", entries: []string{"mob_attack_no_aggro"}},
	{name: "minecraft:no_impact", entries: []string{"drown"}},
	{name: "minecraft:no_knockback", entries: []string{"explosion", "player_explosion", "bad_respawn_point", "in_fire", "lightning_bolt", "on_fire", "lava", "hot_floor", "sulfur_cube_hot", "in_wall", "cramming", "drown", "starve", "cactus", "fall", "ender_pearl", "fly_into_wall", "out_of_world", "generic", "magic", "wither", "dragon_breath", "dry_out", "sweet_berry_bush", "freeze", "stalagmite", "outside_border", "generic_kill", "campfire", "spear"}},
	{name: "minecraft:panic_causes", entries: []string{"cactus", "freeze", "hot_floor", "sulfur_cube_hot", "in_fire", "lava", "lightning_bolt", "on_fire", "arrow", "dragon_breath", "explosion", "fireball", "fireworks", "indirect_magic", "magic", "mob_attack", "mob_projectile", "player_explosion", "sonic_boom", "sting", "thrown", "trident", "unattributed_fireball", "wind_charge", "wither", "wither_skull", "player_attack", "spear", "mace_smash"}},
	{name: "minecraft:panic_environmental_causes", entries: []string{"cactus", "freeze", "hot_floor", "sulfur_cube_hot", "in_fire", "lava", "lightning_bolt", "on_fire"}},
	{name: "minecraft:sulfur_cube_with_block_immune_to", entries: []string{"arrow", "cactus", "dry_out", "fall", "falling_anvil", "falling_block", "falling_stalactite", "freeze", "mace_smash", "hot_floor", "mob_attack", "mob_attack_no_aggro", "mob_projectile", "player_attack", "spear", "spit", "stalagmite", "sting", "sulfur_cube_hot", "sweet_berry_bush", "thrown", "trident", "wind_charge", "fireworks", "explosion", "player_explosion", "bad_respawn_point"}},
	{name: "minecraft:witch_resistant_to", entries: []string{"magic", "indirect_magic", "sonic_boom", "thorns"}},
	{name: "minecraft:wither_immune_to", entries: []string{"drown"}},
}

var tagsBanner = []syncedTag{
	{name: "minecraft:no_item_required", entries: []string{"square_bottom_left", "square_bottom_right", "square_top_left", "square_top_right", "stripe_bottom", "stripe_top", "stripe_left", "stripe_right", "stripe_center", "stripe_middle", "stripe_downright", "stripe_downleft", "small_stripes", "cross", "straight_cross", "triangle_bottom", "triangle_top", "triangles_bottom", "triangles_top", "diagonal_left", "diagonal_up_right", "diagonal_up_left", "diagonal_right", "circle", "rhombus", "half_vertical", "half_horizontal", "half_vertical_right", "half_horizontal_bottom", "border", "gradient", "gradient_up"}},
	{name: "minecraft:pattern_item/bordure_indented", entries: []string{"curly_border"}},
	{name: "minecraft:pattern_item/creeper", entries: []string{"creeper"}},
	{name: "minecraft:pattern_item/field_masoned", entries: []string{"bricks"}},
	{name: "minecraft:pattern_item/flow", entries: []string{"flow"}},
	{name: "minecraft:pattern_item/flower", entries: []string{"flower"}},
	{name: "minecraft:pattern_item/globe", entries: []string{"globe"}},
	{name: "minecraft:pattern_item/guster", entries: []string{"guster"}},
	{name: "minecraft:pattern_item/mojang", entries: []string{"mojang"}},
	{name: "minecraft:pattern_item/piglin", entries: []string{"piglin"}},
	{name: "minecraft:pattern_item/skull", entries: []string{"skull"}},
}

var tagsBlock776 = []syncedTag{
	{name: "minecraft:acacia_logs"},
	{name: "minecraft:air"},
	{name: "minecraft:all_hanging_signs"},
	{name: "minecraft:all_signs"},
	{name: "minecraft:ancient_city_replaceable"},
	{name: "minecraft:animals_spawnable_on"},
	{name: "minecraft:anvil"},
	{name: "minecraft:armadillo_spawnable_on"},
	{name: "minecraft:axolotls_spawnable_on"},
	{name: "minecraft:azalea_grows_on"},
	{name: "minecraft:azalea_root_replaceable"},
	{name: "minecraft:badlands_terracotta"},
	{name: "minecraft:bamboo_blocks"},
	{name: "minecraft:banners"},
	{name: "minecraft:bars"},
	{name: "minecraft:base_stone_nether"},
	{name: "minecraft:base_stone_overworld"},
	{name: "minecraft:bats_spawnable_on"},
	{name: "minecraft:beacon_base_blocks"},
	{name: "minecraft:beds"},
	{name: "minecraft:bee_attractive"},
	{name: "minecraft:bee_growables"},
	{name: "minecraft:beehives"},
	{name: "minecraft:beneath_bamboo_podzol_replaceable"},
	{name: "minecraft:beneath_tree_podzol_replaceable"},
	{name: "minecraft:birch_logs"},
	{name: "minecraft:blocks_wind_charge_explosions"},
	{name: "minecraft:buttons"},
	{name: "minecraft:camel_sand_step_sound_blocks"},
	{name: "minecraft:camels_spawnable_on"},
	{name: "minecraft:campfires"},
	{name: "minecraft:can_glide_through"},
	{name: "minecraft:candle_cakes"},
	{name: "minecraft:candles"},
	{name: "minecraft:cannot_replace_below_tree_trunk"},
	{name: "minecraft:cannot_support_kelp"},
	{name: "minecraft:cannot_support_seagrass"},
	{name: "minecraft:cannot_support_snow_layer"},
	{name: "minecraft:cauldrons"},
	{name: "minecraft:causes_continuous_geyser_eruptions"},
	{name: "minecraft:causes_periodic_geyser_eruptions"},
	{name: "minecraft:cave_vines"},
	{name: "minecraft:ceiling_hanging_signs"},
	{name: "minecraft:chains"},
	{name: "minecraft:cherry_logs"},
	{name: "minecraft:climbable"},
	{name: "minecraft:coal_ores"},
	{name: "minecraft:combination_step_sound_blocks"},
	{name: "minecraft:completes_find_tree_tutorial"},
	{name: "minecraft:concrete"},
	{name: "minecraft:concrete_powders"},
	{name: "minecraft:convertable_to_mud"},
	{name: "minecraft:copper"},
	{name: "minecraft:copper_chests"},
	{name: "minecraft:copper_golem_statues"},
	{name: "minecraft:copper_ores"},
	{name: "minecraft:coral_blocks"},
	{name: "minecraft:coral_plants"},
	{name: "minecraft:corals"},
	{name: "minecraft:crimson_stems"},
	{name: "minecraft:crops"},
	{name: "minecraft:crystal_sound_blocks"},
	{name: "minecraft:dampens_vibrations"},
	{name: "minecraft:dark_oak_logs"},
	{name: "minecraft:deepslate_ore_replaceables"},
	{name: "minecraft:default_immune_to"},
	{name: "minecraft:diamond_ores"},
	{name: "minecraft:dirt"},
	{name: "minecraft:does_not_block_hoppers"},
	{name: "minecraft:doors"},
	{name: "minecraft:dragon_immune"},
	{name: "minecraft:dragon_transparent"},
	{name: "minecraft:dripstone_replaceable_blocks"},
	{name: "minecraft:edible_for_sheep"},
	{name: "minecraft:emerald_ores"},
	{name: "minecraft:enables_bubble_column_drag_down"},
	{name: "minecraft:enables_bubble_column_push_up"},
	{name: "minecraft:enchantment_power_provider"},
	{name: "minecraft:enchantment_power_transmitter"},
	{name: "minecraft:enderman_holdable"},
	{name: "minecraft:fall_damage_resetting"},
	{name: "minecraft:features_cannot_replace"},
	{name: "minecraft:fence_gates"},
	{name: "minecraft:fences"},
	{name: "minecraft:fire"},
	{name: "minecraft:flower_pots"},
	{name: "minecraft:flowers"},
	{name: "minecraft:forest_rock_can_place_on"},
	{name: "minecraft:fox_immune_to"},
	{name: "minecraft:foxes_spawnable_on"},
	{name: "minecraft:frog_prefer_jump_to"},
	{name: "minecraft:frogs_spawnable_on"},
	{name: "minecraft:geode_invalid_blocks"},
	{name: "minecraft:glazed_terracotta"},
	{name: "minecraft:goats_spawnable_on"},
	{name: "minecraft:gold_ores"},
	{name: "minecraft:grass_blocks"},
	{name: "minecraft:grows_crops"},
	{name: "minecraft:guarded_by_piglins"},
	{name: "minecraft:happy_ghast_avoids"},
	{name: "minecraft:hoglin_repellents"},
	{name: "minecraft:huge_brown_mushroom_can_place_on"},
	{name: "minecraft:huge_red_mushroom_can_place_on"},
	{name: "minecraft:ice"},
	{name: "minecraft:ice_spike_replaceable"},
	{name: "minecraft:impermeable"},
	{name: "minecraft:incorrect_for_copper_tool"},
	{name: "minecraft:incorrect_for_diamond_tool"},
	{name: "minecraft:incorrect_for_gold_tool"},
	{name: "minecraft:incorrect_for_iron_tool"},
	{name: "minecraft:incorrect_for_netherite_tool"},
	{name: "minecraft:incorrect_for_stone_tool"},
	{name: "minecraft:incorrect_for_wooden_tool"},
	{name: "minecraft:infiniburn_end"},
	{name: "minecraft:infiniburn_nether"},
	{name: "minecraft:infiniburn_overworld"},
	{name: "minecraft:inside_step_sound_blocks"},
	{name: "minecraft:invalid_spawn_inside"},
	{name: "minecraft:iron_ores"},
	{name: "minecraft:jungle_logs"},
	{name: "minecraft:lanterns"},
	{name: "minecraft:lapis_ores"},
	{name: "minecraft:lava_pool_stone_cannot_replace"},
	{name: "minecraft:leaves"},
	{name: "minecraft:lightning_rods"},
	{name: "minecraft:logs"},
	{name: "minecraft:logs_that_burn"},
	{name: "minecraft:lush_ground_replaceable"},
	{name: "minecraft:maintains_farmland"},
	{name: "minecraft:mangrove_logs"},
	{name: "minecraft:mangrove_logs_can_grow_through"},
	{name: "minecraft:mangrove_roots_can_grow_through"},
	{name: "minecraft:mineable/axe"},
	{name: "minecraft:mineable/hoe"},
	{name: "minecraft:mineable/pickaxe"},
	{name: "minecraft:mineable/shovel"},
	{name: "minecraft:mob_interactable_doors"},
	{name: "minecraft:mooshrooms_spawnable_on"},
	{name: "minecraft:moss_blocks"},
	{name: "minecraft:moss_replaceable"},
	{name: "minecraft:mud"},
	{name: "minecraft:needs_diamond_tool"},
	{name: "minecraft:needs_iron_tool"},
	{name: "minecraft:needs_stone_tool"},
	{name: "minecraft:nether_carver_replaceables"},
	{name: "minecraft:nylium"},
	{name: "minecraft:oak_logs"},
	{name: "minecraft:occludes_vibration_signals"},
	{name: "minecraft:overrides_mushroom_light_requirement"},
	{name: "minecraft:overworld_carver_replaceables"},
	{name: "minecraft:overworld_natural_logs"},
	{name: "minecraft:pale_oak_logs"},
	{name: "minecraft:parrots_spawnable_on"},
	{name: "minecraft:piglin_repellents"},
	{name: "minecraft:planks"},
	{name: "minecraft:polar_bear_immune_to"},
	{name: "minecraft:polar_bears_spawnable_on_alternate"},
	{name: "minecraft:portals"},
	{name: "minecraft:pressure_plates"},
	{name: "minecraft:prevent_mob_spawning_inside"},
	{name: "minecraft:prevents_nearby_leaf_decay"},
	{name: "minecraft:rabbits_spawnable_on"},
	{name: "minecraft:rails"},
	{name: "minecraft:redstone_ores"},
	{name: "minecraft:replaceable"},
	{name: "minecraft:replaceable_by_mushrooms"},
	{name: "minecraft:replaceable_by_trees"},
	{name: "minecraft:sand"},
	{name: "minecraft:saplings"},
	{name: "minecraft:sculk_replaceable"},
	{name: "minecraft:sculk_replaceable_world_gen"},
	{name: "minecraft:shears_extreme_breaking_speed"},
	{name: "minecraft:shears_major_breaking_speed"},
	{name: "minecraft:shears_minor_breaking_speed"},
	{name: "minecraft:shulker_boxes"},
	{name: "minecraft:signs"},
	{name: "minecraft:slabs"},
	{name: "minecraft:small_flowers"},
	{name: "minecraft:smelts_to_glass"},
	{name: "minecraft:snaps_goat_horn"},
	{name: "minecraft:sniffer_diggable_block"},
	{name: "minecraft:sniffer_egg_hatch_boost"},
	{name: "minecraft:snow"},
	{name: "minecraft:snow_golem_immune_to"},
	{name: "minecraft:soul_fire_base_blocks"},
	{name: "minecraft:soul_speed_blocks"},
	{name: "minecraft:speleothems"},
	{name: "minecraft:spruce_logs"},
	{name: "minecraft:stairs"},
	{name: "minecraft:standing_signs"},
	{name: "minecraft:stone_bricks"},
	{name: "minecraft:stone_buttons"},
	{name: "minecraft:stone_ore_replaceables"},
	{name: "minecraft:stone_pressure_plates"},
	{name: "minecraft:stray_immune_to"},
	{name: "minecraft:strider_warm_blocks"},
	{name: "minecraft:substrate_overworld"},
	{name: "minecraft:sulfur_spike_replaceable_blocks"},
	{name: "minecraft:support_override_cactus_flower"},
	{name: "minecraft:support_override_snow_layer"},
	{name: "minecraft:supports_azalea"},
	{name: "minecraft:supports_bamboo"},
	{name: "minecraft:supports_big_dripleaf"},
	{name: "minecraft:supports_cactus"},
	{name: "minecraft:supports_chorus_flower"},
	{name: "minecraft:supports_chorus_plant"},
	{name: "minecraft:supports_cocoa"},
	{name: "minecraft:supports_crimson_fungus"},
	{name: "minecraft:supports_crimson_roots"},
	{name: "minecraft:supports_crops"},
	{name: "minecraft:supports_dry_vegetation"},
	{name: "minecraft:supports_frogspawn"},
	{name: "minecraft:supports_hanging_mangrove_propagule"},
	{name: "minecraft:supports_lily_pad"},
	{name: "minecraft:supports_mangrove_propagule"},
	{name: "minecraft:supports_melon_stem"},
	{name: "minecraft:supports_melon_stem_fruit"},
	{name: "minecraft:supports_nether_sprouts"},
	{name: "minecraft:supports_nether_wart"},
	{name: "minecraft:supports_pumpkin_stem"},
	{name: "minecraft:supports_pumpkin_stem_fruit"},
	{name: "minecraft:supports_small_dripleaf"},
	{name: "minecraft:supports_stem_crops"},
	{name: "minecraft:supports_stem_fruit"},
	{name: "minecraft:supports_sugar_cane"},
	{name: "minecraft:supports_sugar_cane_adjacently"},
	{name: "minecraft:supports_vegetation"},
	{name: "minecraft:supports_warped_fungus"},
	{name: "minecraft:supports_warped_roots"},
	{name: "minecraft:supports_wither_rose"},
	{name: "minecraft:suppresses_bounce"},
	{name: "minecraft:sword_efficient"},
	{name: "minecraft:sword_instantly_mines"},
	{name: "minecraft:terracotta"},
	{name: "minecraft:trail_ruins_replaceable"},
	{name: "minecraft:trapdoors"},
	{name: "minecraft:triggers_ambient_desert_dry_vegetation_block_sounds"},
	{name: "minecraft:triggers_ambient_desert_sand_block_sounds"},
	{name: "minecraft:triggers_ambient_dried_ghast_block_sounds"},
	{name: "minecraft:underwater_bonemeals"},
	{name: "minecraft:unstable_bottom_center"},
	{name: "minecraft:valid_spawn"},
	{name: "minecraft:vibration_resonators"},
	{name: "minecraft:wall_corals"},
	{name: "minecraft:wall_hanging_signs"},
	{name: "minecraft:wall_post_override"},
	{name: "minecraft:wall_signs"},
	{name: "minecraft:walls"},
	{name: "minecraft:warped_stems"},
	{name: "minecraft:wart_blocks"},
	{name: "minecraft:wither_immune"},
	{name: "minecraft:wither_immune_to"},
	{name: "minecraft:wither_skeleton_immune_to"},
	{name: "minecraft:wither_summon_base_blocks"},
	{name: "minecraft:wolves_spawnable_on"},
	{name: "minecraft:wooden_buttons"},
	{name: "minecraft:wooden_doors"},
	{name: "minecraft:wooden_fences"},
	{name: "minecraft:wooden_pressure_plates"},
	{name: "minecraft:wooden_shelves"},
	{name: "minecraft:wooden_slabs"},
	{name: "minecraft:wooden_stairs"},
	{name: "minecraft:wooden_trapdoors"},
	{name: "minecraft:wool"},
	{name: "minecraft:wool_carpets"},
}

// Tag payload one protocol requires to load
func syncedTagSet(protocol int32) []syncedTagRegistry {
	switch {
	case protocol >= 776:
		return []syncedTagRegistry{
			{name: "minecraft:dialog", tags: tagsDialog},
			{name: "minecraft:timeline", tags: tagsTimeline},
			{name: "minecraft:damage_type", tags: tagsDamage776},
			{name: "minecraft:banner_pattern", tags: tagsBanner},
			{name: "minecraft:block", tags: tagsBlock776},
		}
	case protocol >= 775:
		return []syncedTagRegistry{
			{name: "minecraft:dialog", tags: tagsDialog},
			{name: "minecraft:timeline", tags: tagsTimeline},
			{name: "minecraft:damage_type", tags: tagsDamage775},
			{name: "minecraft:banner_pattern", tags: tagsBanner},
		}
	case protocol >= 774:
		return []syncedTagRegistry{
			{name: "minecraft:dialog", tags: tagsDialog},
			{name: "minecraft:timeline", tags: tagsTimeline},
		}
	case protocol >= 771:
		return []syncedTagRegistry{
			{name: "minecraft:dialog", tags: tagsDialog},
		}
	default:
		return nil
	}
}
